apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: default
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: system
      metricsets: ["cpu", "memory", "network", "process", "core", "diskio"]
      enabled: true
      period: 10s
      processes: ['.*']
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:7.9.3
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          name: metricbeat-config
          defaultMode: 0644
