apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: ngeuya/ame-mysql
          ports:
            - containerPort: 3306
          volumeMounts: 
          - name: mysql-storage
            mountPath: /var/lib/mysql
          # Definir les Probes  pour vérifier l'état des conteneurs dans un pod.
          livenessProbe: #Vérifie si le conteneur fonctionne correctement. Si la vérification échoue, le conteneur est redémarré
            exec:
              command: #vérifie si le serveur MySQL répond.
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 30  # Temps d'attente avant le premier test
            periodSeconds: 10        # Fréquence de vérification
          readinessProbe:  #Vérifie si le conteneur est prêt à recevoir du trafic. Si la vérification échoue, le conteneur est retiré du service (Service endpoint).
            exec: #assure que le serveur MySQL est prêt.
              command:
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 15  # Temps d'attente avant le premier test
            periodSeconds: 5         # Fréquence de vérification
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc