apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers :
        - name: web
          image: ngeuya/ame-apache
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
                path: /
                port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10





# ---


##Ajuster le nombre de réplicas d'un déploiement
###Basé sur des métriques comme l'utilisation du CPU ou de la mémoire
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: apache-hpa
# spec:
#   maxReplicas: 5
#   minReplicas: 1
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: apache-deployment
#   targetCPUUtilizationPercentage: 50